### ISSUE TITLE
Requested resource is current not available

### ISSUE THREAD

**Issue by hildebrau** [xur17/southwest-alerts#12]
While running xur17/southwest-alerts docker container recently, I'm seeing this error when I follow the logs of the container as it executes:

```
{"code":503500001,"message":"Requested resource is currently not available.","httpStatusCode":"SERVICE_UNAVAILABLE","requestId":"x22qB7r7QbK6NwpsqSju_A-API"}
Traceback (most recent call last):
  File "/app/southwestalerts/app.py", line 72, in <module>
    check_for_price_drops(user.username, user.password, user.email)
  File "/app/southwestalerts/app.py", line 34, in check_for_price_drops
    destination_airport
  File "/app/southwestalerts/southwest.py", line 62, in get_available_flights
    return self._session.get(url)
  File "/app/southwestalerts/southwest.py", line 80, in get
    return self._parsed_response(resp, success_codes=success_codes)
  File "/app/southwestalerts/southwest.py", line 101, in _parsed_response
    raise Exception('Invalid status code received. Expected {}. Received {}.'.format(success_codes, response.status_code))
Exception: Invalid status code received. Expected [200]. Received 503.
```

What should I do?

**Comment by hildebrau** [comment]
Oops.  I pulled down the latest image and it seems to work fine.  My bad.  Closing this .
