### ISSUE TITLE
ERROR__DATE_CAN_NOT_BE_PAST

### ISSUE THREAD

**Issue by hildebrau** [xur17/southwest-alerts#14]
I'm "mid-itinerary" currently.  I flew one leg of an open-jaw itinerary yesterday (12/20).  Today when the southwest-alerts script runs, it outputs the following (w/ my latest unapproved patch applied, btw)

`INFO:root:itinerary original total price: 7691
{"code":400521120,"message":"Date cannot be in the past","messageKey":"ERROR__DATE_CAN_NOT_BE_PAST","httpStatusCode":"BAD_REQUEST","requestId":"no-exp-id:8_nRFx82QNWa30J4Iu4lZw:unknown","infoList":[{"key":"flight date-1","value":"Date is in the past:2018-12-20T00:00:00.000-06:00"}]}
Traceback (most recent call last):
  File "/app/southwestalerts/app.py", line 87, in <module>
    check_for_price_drops(user.username, user.password, user.email)
  File "/app/southwestalerts/app.py", line 39, in check_for_price_drops
    destination_airport
  File "/app/southwestalerts/southwest.py", line 62, in get_available_flights
    return self._session.get(url)
  File "/app/southwestalerts/southwest.py", line 80, in get
    return self._parsed_response(resp, success_codes=success_codes)
  File "/app/southwestalerts/southwest.py", line 101, in _parsed_response
    raise Exception('Invalid status code received. Expected {}. Received {}.'.format(success_codes, response.status_code))
Exception: Invalid status code received. Expected [200]. Received 400.
`

It looks like it's still seeing yesterday's leg of my confirmation numbers and it is trying to look those up still.  We should probably check for past dates and skip those flight legs in the calculations.  That may mess with the math, however.  Probably best to just skip the entire confirmation number if any of the dates are in the past.

**Comment by joshjohanning** [comment]
Ahh. I've only done booked one ways but this makes sense.
